id: block_url_-_generic
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Block URL - Generic
description: |-
  This playbook blocks malicious URLs using all integrations that are enabled.

  Supported integrations for this playbook:
  * Palo Alto Networks Minemeld
  * Palo Alto Networks PAN-OS
  * Zscaler
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 59b1a1c8-41a6-4b2f-8bb4-24e4bd1036d8
    type: start
    task:
      id: 59b1a1c8-41a6-4b2f-8bb4-24e4bd1036d8
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 257.5,
          "y": 30
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 5ba81cb8-30c1-4d31-8af6-45f937d1d58b
    type: title
    task:
      id: 5ba81cb8-30c1-4d31-8af6-45f937d1d58b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 257.5,
          "y": 980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 21e74ef4-5adb-44a4-874b-2bedbd59a051
    type: title
    task:
      id: 21e74ef4-5adb-44a4-874b-2bedbd59a051
      version: -1
      name: Block URLs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "17"
      - "18"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1140,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 6685a431-51a7-4bf8-8679-5d079a8dca85
    type: condition
    task:
      id: 6685a431-51a7-4bf8-8679-5d079a8dca85
      version: -1
      name: Is there a URL to block?
      description: Verify that the playbook input includes at least one URL to block.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.URL
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 257.5,
          "y": 165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 4270c78b-8b35-44c8-832a-11b82fbbd9c4
    type: condition
    task:
      id: 4270c78b-8b35-44c8-832a-11b82fbbd9c4
      version: -1
      name: Is Zscaler enabled?
      description: Verify that there is a valid instance of Zscaler enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Zscaler
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1500,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 6c17067d-ac81-454b-8c4b-77e38811443e
    type: regular
    task:
      id: 6c17067d-ac81-454b-8c4b-77e38811443e
      version: -1
      name: Block URL with Zscaler
      description: Block the URLS using Zscaler.
      script: '|||zscaler-blacklist-url'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1500,
          "y": 805
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: fa3391b8-020e-4f53-8576-7445bf741452
    type: playbook
    task:
      id: fa3391b8-020e-4f53-8576-7445bf741452
      version: -1
      name: PAN-OS - Block URL - Custom URL Category
      playbookName: PAN-OS - Block URL - Custom URL Category
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 530,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: e92be57f-773d-496a-80f0-b1bc292b5355
    type: title
    task:
      id: e92be57f-773d-496a-80f0-b1bc292b5355
      version: -1
      name: PAN-OS
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "19"
      - "20"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 770,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 18d080a9-f73c-4394-8f59-8cb602fd1604
    type: title
    task:
      id: 18d080a9-f73c-4394-8f59-8cb602fd1604
      version: -1
      name: Zscaler
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1500,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 663d099d-dde1-4521-8ff2-18fabf06d99e
    type: condition
    task:
      id: 663d099d-dde1-4521-8ff2-18fabf06d99e
      version: -1
      name: Use EDL?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "21"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.EDLServerIP
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1020,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 61ddf243-2502-4c31-8ae3-9333c488d492
    type: condition
    task:
      id: 61ddf243-2502-4c31-8ae3-9333c488d492
      version: -1
      name: Use Custom URL Category?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.type
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 530,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 64804b25-6237-4461-886c-dac1e9a1905d
    type: regular
    task:
      id: 64804b25-6237-4461-886c-dac1e9a1905d
      version: -1
      name: ADD EDL Tag To URL Indicators
      description: commands.local.cmd.add.values.to.indicator.multi.select.field
      script: Builtin|||appendIndicatorField
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        complex:
          root: inputs.EDLTag
      indicatorsValues:
        complex:
          root: inputs.URL
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1020,
          "y": 805
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
system: true
view: |-
  {
    "linkLabelsPosition": {
      "12_2_#default#": 0.48,
      "8_2_#default#": 0.43
    },
    "paper": {
      "dimensions": {
        "height": 1015,
        "width": 1622.5,
        "x": 257.5,
        "y": 30
      }
    }
  }
inputs:
- key: URL
  value: {}
  required: false
  description: Array of malicious URLs to block.
  playbookInputQuery:
- key: LogForwarding
  value: {}
  required: false
  description: Log Forwarding object name.
  playbookInputQuery:
- key: EDLServerIP
  value: {}
  required: false
  description: EDL server IP address.
  playbookInputQuery:
- key: AutoCommit
  value:
    simple: "No"
  required: false
  description: |-
    This input establishes whether to commit the configuration automatically.
    Yes - Commit automatically.
    No - Commit manually.
  playbookInputQuery:
- key: CustomURLCategory
  value:
    simple: Demisto Remediation - Malicious URLs
  required: false
  description: Custom URL Category name.
  playbookInputQuery:
- key: type
  value: {}
  required: false
  description: Custom URL category type. Insert "URL List"/ "Category Match".
  playbookInputQuery:
- key: device-group
  value: {}
  required: false
  description: Device group for the Custom URL Category (Panorama instances).
  playbookInputQuery:
- key: categories
  value: {}
  required: false
  description: The list of categories. Relevant from PAN-OS v9.x.
  playbookInputQuery:
- key: EDLTag
  value: {}
  required: false
  description: Insert a tag name with which indicators will get tagged. This tag can be used later in the External Dynamic Lists integration by using the tag for filtering IPs in the indicator query.
  playbookInputQuery:
outputs: []
fromversion: 5.0.0
tests:
- block_indicators_-_generic_-_test
marketplaces:
  - xsoar
  - marketplacev2